spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: web-server
          uri: http://localhost:8001
          predicates:
            - Path=/gateway/web/**
            - Query=web
          filters:
            - StripPrefix=1
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/eureka
server:
  port: 8020
  servlet:
    context-path: /gateway
