server:
  port: 8002
  servlet:
    context-path: /cache

spring:
  application:
    name: cache-server
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: off